export const GET_NETFLIX_ORIGINALS = "GET_NETFLIX_ORIGINALS";
export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_TOP_RATED = "GET_TOP_RATED";
export const GET_ACTION_MOVIE = "GET_TOP_MOVIE";
export const GET_SEARCH_MOVIE = "GET_SEARCH_MOVIE";

export const SET_MOVIE_DETAIL = "SET_MOVIE_DETAIL";
